### ISSUE TITLE
Unable to install packages  in R

### ISSUE THREAD

**Issue by kduchrow** [AnalyticsEarth/qlik-k8s-demo-resources#1]
Hi,
is it possible to install additional Packages in R?
I tried to install the Package in the Qlik script like : 
`DataTableTest:Load * Extension R.ScriptEvalStr('install.packages("data.table");library(data.table);data.table(test = c(10:10000))');`

But I got this error : 
> |WARN|SSEtoRserve.RServeEvaluator|Rserve error: Error in install.packages("data.table") : unable to install packages

I also tried to install the Package by entering the R CLI but I also got an error.

> Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in install.packages("data.table") :
  'lib = "/usr/local/lib/R/site-library"' is not writable
Would you like to use a personal library instead? (yes/No/cancel) n
Error in install.packages("data.table") : unable to install packages

**Comment by kduchrow** [comment]
Ok, I got it. 
First of all, I connected to the container as root user, that I can Install the Package manually.
`sudo docker exec -it -u root containerID bin/bash`

After that, I realized, that the R.ScriptEvalStr Method isn't able to give back data.table objects, so they need to be converted.

`DataTableTest:
Load * Extension R.ScriptEvalStr('library(data.table); as.data.frame(data.table(test = c(1:10000)))');`

But this does not fix the problem completely. 
If the container restarts, the plugins need to be reinstalled every time. 
Maybe it could be possible to define additional Packages in the values.yaml ?

**Comment by AnalyticsEarth** [comment]
packages need to be installed in the container, there is a process for this. So more can be added using the build script. When changes are added they get added to a new version of the container. If you have some packages you would like to use let me know and I can add them to the build process. The container is not created in this repo, so will need a pull request on a different one.

**Comment by AnalyticsEarth** [comment]
you can add a pull request to this file (or let me know the packages to add), once changes are merged, the container should be updated within an hour on docker hub. https://github.com/AnalyticsEarth/sse-r-plugin/blob/master/docker/packages_dist/installpackages.r

**Comment by kduchrow** [comment]
OK, thank you for your Answer!
This should work fine for my use case.
But in my opinion, this could not be the Final Solution. 
In my thoughts there need to be an opportunity to add additional libraries easily into the container. 
As I can see, you add the librarys in the build section, so the libraries needed for Rserve are installed while building. If you want everybody add their libraries to this, the container will be very large. 
Couldn't it be possible, to define a second "package installation part", where you can define needed libraries (as a string array ) in the values.yaml and install it in the entry point section. This could cause a slightly longer start time, but increases the customization possibilities.

**Comment by AnalyticsEarth** [comment]
Hi, this is a generic container but would expect people setting up their own environment to build their own R container image with the packages they need. You can just swap out your own container in the values file.

Its bad practice to install at load time (this container takes approx 30m to build and install the packages.) If this was at run time then it would not be able to scale or recover from node migrations without a long transition or downtime.

You can then approve the packages you need and have approved for your use cases and add to your own container, within your CI/CD processes.

**Comment by kduchrow** [comment]
So I only need to add these lines to the values : 
```
sse2rserve:
  enabled: true
  rserve:
    image:
      repository: my-own-image
      tag: latest
      pullPolicy: Always
      resources: {}
```
Build my own image with added packages and I'm good to go right?

**Comment by AnalyticsEarth** [comment]
yes that's correct, the connector is in a separate image in the pod, so you just need to build the rserve image.

You only need to build the image from the dockerfile: https://github.com/AnalyticsEarth/sse-r-plugin/blob/master/csharp/Dockerfile-k8-rserve

this only needs the package install script and does not need any compiling of the connector.

**Comment by kduchrow** [comment]
Okay I will try this. Thank you!
